services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: do_cours_1
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - 127.0.0.1:5433:5432

volumes:
  db-data: { }
